--- 
title: "Data science with R: Applied Predictive Modelling"
subtitle: "Compendium for STAT623"
author: "Sondre Hølleland and Kristian Gundersen"
date: "`r Sys.time()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
chunk_output_type: console
description: "Course in applied predictive modelling made for teaching STAT623 at University of Bergen"
---

# Course overview {-}

## Learning outcomes and objectives{-}
The course presents various advanced methods within data science for predictive modelling and the use of R. Methods for regression, including non-linear regression and generalized additive models, and methods for classification, including trees, boosting and Support Vector Machines, will be examined. The course will focus on practical use in r, without going into details of the mathematical theory of the methods. 

On completion of the course the student should have the following learning outcomes:

####  Knowledge{-}

- Knows the basic ideas underpinning carious methods in data science/predictive modelling

#### Skills{-}

- Can implement various models within data science/predictive modelling in R
- Use data science methods on real data sets and perform predictions

#### General competence{-}

- Have an overview of how data science methods can be used to analyze larger data sets

## Lecture overview {-}

```{r, echo = FALSE}
Lectures <- data.frame(
  Lecture = paste0("\\@ref(lecture",1:9,")"),
  Subject = c("Introduction and short recap of R and Data preprocessing",
              "Over-fitting and model tuning, selection and evaluation and multiple regression",
              "Non-linear regression",
              "Classification methods",
              "Decision Trees and Bagged trees",
              "Random forrest and boosting",
              "Support vector machines",
              "Neural Networks",
              #"Unsupervised learning",
              "Feature selection"),
  Exercises = c("Recap of R",
                "Multiple regression",
                "GAMs",
                "","",
                "xgboost", 
                rep("",3)),
  "Datacamp" = c("Introduction to Regression in R (ch 1-2)",
                 "Supervised Learning in R: Regression (ch 1-2)",
                 "Nonlinear modeling in R with GAMs (ch 1-2)",
                 "Supervised Learning in R: Classification (ch 1-3)",
                 "Machine Learning with Tree-Based Models in R (ch 1-3)",
                  "Machine Learning with Tree-Based Models in R (ch 3-4)",
                 "Support Vector Machines in R (ch 1-2)",
                 "Introduction to TensorFlow in R (ch 1-3)",
                 #"Unsupervised Learning in R (ch 1-4)",
                 "Supervised Learning in R: Classification (ch 3, video on automatic feature selection")
)
knitr::kable(Lectures)
```

## Litterature {-}

We will use many different sources for teaching you applied predictive modelling. @kuhn2016 and @james2013 are the main references. 


